services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    networks:
      - backend-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    restart: unless-stopped
    networks:
      - app-network
      

networks:
  app-network:
    driver: bridge
  backend-network:
    driver: bridge