# Build stage
FROM maven:3.9.9-eclipse-temurin-23 AS builder
WORKDIR /usr/app
COPY pom.xml .
RUN mvn dependency:go-offline
COPY src ./src
RUN mvn clean package -DskipTests

# Runtime stage
FROM eclipse-temurin:23-jre-alpine
WORKDIR /app
COPY --from=builder /usr/app/target/*.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]